### ISSUE TITLE
gen_array.py

### ISSUE THREAD

**Issue by mhsszm** [kendryte/kendryte-model-compiler#2]
You will find a python script named ```gen_array.py``` in ```kendryte-standalone-sdk/src/kpu/``` ,i can't find the script in 'kendryte-standalone-sdk/src/kpu/',where i can get it ??

**Comment by 0x00-pl** [comment]
you can find it in here:
https://github.com/kendryte/kendryte-standalone-demo/blob/master/kpu/gen_array.py
