### ISSUE TITLE
run yolo  demo 

### ISSUE THREAD

**Issue by mhsszm** [kendryte/kendryte-model-compiler#9]
gencode_output.c:26781:8: error: 'kpu_task_t {aka struct <anonymous>}' has no member named 'layers_length'; did you mean 'dst_length'?

**Comment by mhsszm** [comment]
![22](https://user-images.githubusercontent.com/25781417/48763540-75ef8780-ece8-11e8-80ee-1dc5a40b2cb6.png)

**Comment by manageryzy** [comment]
update your kendryte standalone sdk
